boot.o: boot.S multiboot.h x86_desc.h types.h
linkage.o: linkage.S
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
interrupt.o: interrupt.c x86_desc.h types.h lib.h interrupt.h linkage.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h interrupt.h
lib.o: lib.c lib.h types.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
