boot.o: boot.S multiboot.h x86_desc.h types.h
linkage.o: linkage.S
syscall_handler.o: syscall_handler.S x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
filesystem.o: filesystem.c filesystem.h lib.h types.h pcb.h x86_desc.h \
  system_calls.h terminal.h keyboard.h i8259.h definitions.h schedule.h \
  rtc.h paging.h
i8259.o: i8259.c i8259.h types.h lib.h
interrupt.o: interrupt.c x86_desc.h types.h lib.h linkage.h interrupt.h \
  i8259.h keyboard.h terminal.h schedule.h definitions.h rtc.h paging.h \
  pcb.h system_calls.h filesystem.h pit.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h interrupt.h rtc.h keyboard.h terminal.h schedule.h \
  definitions.h paging.h pcb.h system_calls.h filesystem.h pit.h
keyboard.o: keyboard.c keyboard.h i8259.h types.h lib.h terminal.h \
  schedule.h definitions.h x86_desc.h rtc.h paging.h pcb.h system_calls.h \
  filesystem.h
lib.o: lib.c lib.h types.h keyboard.h i8259.h terminal.h schedule.h \
  definitions.h x86_desc.h rtc.h paging.h pcb.h system_calls.h \
  filesystem.h
paging.o: paging.c paging.h lib.h types.h pcb.h x86_desc.h system_calls.h \
  filesystem.h terminal.h keyboard.h i8259.h definitions.h schedule.h \
  rtc.h
pcb.o: pcb.c pcb.h x86_desc.h types.h system_calls.h filesystem.h lib.h \
  terminal.h keyboard.h i8259.h definitions.h schedule.h rtc.h paging.h
pit.o: pit.c pit.h i8259.h types.h schedule.h lib.h definitions.h \
  terminal.h keyboard.h system_calls.h rtc.h paging.h pcb.h x86_desc.h \
  filesystem.h
rtc.o: rtc.c rtc.h types.h lib.h i8259.h
schedule.o: schedule.c schedule.h types.h lib.h definitions.h terminal.h \
  keyboard.h i8259.h system_calls.h rtc.h paging.h pcb.h x86_desc.h \
  filesystem.h
system_calls.o: system_calls.c system_calls.h types.h lib.h filesystem.h \
  rtc.h pcb.h x86_desc.h terminal.h keyboard.h i8259.h definitions.h \
  schedule.h paging.h
terminal.o: terminal.c terminal.h lib.h types.h keyboard.h i8259.h \
  system_calls.h definitions.h schedule.h x86_desc.h rtc.h paging.h pcb.h \
  filesystem.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h paging.h pcb.h \
  system_calls.h filesystem.h terminal.h keyboard.h i8259.h definitions.h \
  schedule.h rtc.h tests/rtc_tests.h tests/../rtc.h tests/../lib.h \
  tests/../tests.h tests/terminal_tests.h tests/../terminal.h \
  tests/filesystem_tests.h tests/../filesystem.h tests/../types.h \
  tests/pcb_tests.h tests/../pcb.h
filesystem_tests.o: tests/filesystem_tests.c tests/filesystem_tests.h \
  tests/../filesystem.h tests/../lib.h tests/../types.h tests/../lib.h \
  tests/../tests.h tests/../types.h
idt_tests.o: tests/idt_tests.c tests/idt_tests.h
paging_tests.o: tests/paging_tests.c tests/paging_tests.h
pcb_tests.o: tests/pcb_tests.c tests/pcb_tests.h tests/../pcb.h \
  tests/../x86_desc.h tests/../types.h tests/../system_calls.h \
  tests/../filesystem.h tests/../lib.h tests/../terminal.h \
  tests/../keyboard.h tests/../i8259.h tests/../definitions.h \
  tests/../schedule.h tests/../rtc.h tests/../paging.h tests/../pcb.h \
  tests/../lib.h
rtc_tests.o: tests/rtc_tests.c tests/rtc_tests.h tests/../rtc.h \
  tests/../types.h tests/../lib.h tests/../tests.h
terminal_tests.o: tests/terminal_tests.c tests/terminal_tests.h \
  tests/../terminal.h tests/../lib.h tests/../types.h tests/../keyboard.h \
  tests/../i8259.h tests/../terminal.h tests/../system_calls.h \
  tests/../definitions.h tests/../schedule.h tests/../x86_desc.h \
  tests/../rtc.h tests/../paging.h tests/../pcb.h tests/../filesystem.h \
  tests/../lib.h tests/../tests.h
