boot.o: boot.S multiboot.h x86_desc.h types.h
linkage.o: linkage.S
x86_desc.o: x86_desc.S x86_desc.h types.h
filesystem.o: filesystem.c filesystem.h lib.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
interrupt.o: interrupt.c x86_desc.h types.h lib.h linkage.h interrupt.h \
  i8259.h keyboard.h terminal.h rtc.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h interrupt.h rtc.h keyboard.h terminal.h paging.h filesystem.h
keyboard.o: keyboard.c keyboard.h i8259.h types.h lib.h terminal.h
lib.o: lib.c lib.h types.h keyboard.h i8259.h terminal.h
paging.o: paging.c paging.h lib.h types.h
rtc.o: rtc.c rtc.h types.h lib.h i8259.h
terminal.o: terminal.c terminal.h lib.h types.h keyboard.h i8259.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h paging.h rtc.h \
  terminal.h keyboard.h i8259.h filesystem.h
